// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
