// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/models/global';
import model_2 from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
