/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./src/components/SurveyComs/EditItems/coms/ButtonGroup.vue')['default']
    ColorEditor: typeof import('./src/components/SurveyComs/EditItems/ColorEditor.vue')['default']
    DescEditor: typeof import('./src/components/SurveyComs/EditItems/DescEditor.vue')['default']
    EditPannel: typeof import('./src/components/SurveyComs/EditItems/EditPannel.vue')['default']
    EditPanner: typeof import('./src/components/SurveyComs/EditItems/EditPanner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGropu: typeof import('element-plus/es')['ElRadioGropu']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/Common/Header.vue')['default']
    ItalicEditor: typeof import('./src/components/SurveyComs/EditItems/ItalicEditor.vue')['default']
    MaterialsHeader: typeof import('./src/components/SurveyComs/Common/MaterialsHeader.vue')['default']
    MultiPicSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/MultiPicSelect.vue')['default']
    MultiSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/MultiSelect.vue')['default']
    OptionsEditor: typeof import('./src/components/SurveyComs/EditItems/OptionsEditor.vue')['default']
    OptionSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/OptionSelect.vue')['default']
    PicItem: typeof import('./src/components/SurveyComs/Common/PicItem.vue')['default']
    PicOptionsEditor: typeof import('./src/components/SurveyComs/EditItems/PicOptionsEditor.vue')['default']
    PositionEditor: typeof import('./src/components/SurveyComs/EditItems/PositionEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePicSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/SinglePicSelect.vue')['default']
    SingleSelect: typeof import('./src/components/SurveyComs/Materials/SelectComs/SingleSelect.vue')['default']
    SizeEditor: typeof import('./src/components/SurveyComs/EditItems/SizeEditor.vue')['default']
    TitleEditor: typeof import('./src/components/SurveyComs/EditItems/TitleEditor.vue')['default']
    WeightEditor: typeof import('./src/components/SurveyComs/EditItems/WeightEditor.vue')['default']
  }
}
