// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import UserOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TeamOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import ReadOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ReadOutlined';
import EditOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/EditOutlined';
import ProfileOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CalendarOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
import AppstoreOutlined from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
export default { HomeOutlined, UserOutlined, TeamOutlined, ReadOutlined, EditOutlined, ProfileOutlined, CalendarOutlined, AppstoreOutlined };
