// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/login","menuRender":false,"parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"首页","path":"/home","icon":"HomeOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"管理员","path":"/admin","icon":"UserOutlined","access":"SuperAdmin","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"管理员列表","path":"adminList","parentId":"4","id":"5"},"6":{"name":"添加管理员","path":"addAdmin","parentId":"4","id":"6"},"7":{"name":"用户","path":"/user","icon":"TeamOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"用户列表","path":"userList","parentId":"7","id":"8"},"9":{"name":"添加用户","path":"addUser","parentId":"7","id":"9"},"10":{"name":"编辑用户","path":"editUser/:id","hideInMenu":true,"parentId":"7","id":"10"},"11":{"name":"书籍","path":"/book","icon":"ReadOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"11"},"12":{"name":"书籍列表","path":"bookList","parentId":"11","id":"12"},"13":{"name":"添加书籍","path":"addBook","parentId":"11","id":"13"},"14":{"name":"编辑书籍","path":"editBook/:id","hideInMenu":true,"parentId":"11","id":"14"},"15":{"name":"面试题","path":"/interview","icon":"EditOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"15"},"16":{"name":"问答","path":"/issue","icon":"ProfileOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"16"},"17":{"name":"评论","path":"/comment","icon":"CalendarOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"17"},"18":{"name":"类型","path":"/type","icon":"AppstoreOutlined","access":"NormalAdmin","parentId":"ant-design-pro-layout","id":"18"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.jsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.jsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Admin__index" */'@/pages/Admin/index.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Admin__addAdmin" */'@/pages/Admin/addAdmin.jsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__User__index" */'@/pages/User/index.jsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__User__addUser" */'@/pages/User/addUser.jsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__User__editUser" */'@/pages/User/editUser.jsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Book__index" */'@/pages/Book/index.jsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Book__addBook" */'@/pages/Book/addBook.jsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Book__editBook" */'@/pages/Book/editBook.jsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Interview__index" */'@/pages/Interview/index.jsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Issue__index" */'@/pages/Issue/index.jsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Comment__index" */'@/pages/Comment/index.jsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Type__index" */'@/pages/Type/index.jsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
