// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-access';
export { connect, useDispatch, useStore, useSelector, getDvaApp } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-dva';
export { Provider, useModel } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-access/types.d';
export * from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-antd/types.d';
export * from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-dva/types.d';
export * from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-layout/types.d';
export * from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/renderer-react';
export type { History } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/xiechen/Documents/code-personal/s-duyi/React/13/background-system2/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
